default: &default
  adapter: mysql2
  encoding: utf8
  database: vine_civicrm
  pool: <%= ENV['DB_POOL'] || 10 %>
  username: root
  password:

development:
  <<: *default
  timeout: <%= ENV['DB_TIMEOUT'] || 10 %>
  reaping_frequency: <%= ENV['DB_REAP_FREQ'] || 10 %>
