# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc2140cdf338c540d1a94b7916cce733b0a85f4e454bec69356214ab64e303fa9382c41834a5c1f7927d08fcec81920a761742bef59bf3c5f50008fdad8351c

test:
  secret_key_base: d5afca8038b9593d2f2c9d768bbcdb79669e78ce0fcb8e25c86a15dc81c66804eb50d44b5a43faa0acccbc1b5c3fc9be9d30ffa7e8e4c5d8992d92e4b75be898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
